services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui:latest
    container_name: iter_swagger_ui
    environment:
      SWAGGER_JSON: /swagger-ui/specification.yml
    networks:
      - public_network
    volumes:
      - ./docs/specification.yml:/swagger-ui/specification.yml

  open-dpp-api:
    image: marguillat/iter-open-dpp-api
    container_name: open_dpp_api
    ports:
      - 7000:7000
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'curl', 'http://127.0.0.1:7000/health']
      interval: 10s
      timeout: 5s
      retries: 3

# Compose networks
networks:
  internal_network:
    external: false
  public_network:
    external: true
