services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui:latest
    container_name: iter_swagger_ui
    environment:
      SWAGGER_JSON: /swagger-ui/specification.yml
    networks:
      - public_network
    volumes:
      - ./open-api/docs/specification.yml:/swagger-ui/specification.yml

  open-dpp-api:
    image: ghcr.io/marguillat/iter-open-api
    container_name: open_dpp_api
    environment:
      ITER_DATABASE_URL: postgresql://user-iter-open:psswd-iter-open@open_dpp_db:5432/db-iter-open
    networks:
      - internal_network
      - public_network
    depends_on:
      open-dpp-db:
        condition: service_healthy

  open-dpp-db:
    image: postgres:18
    restart: unless-stopped
    container_name: open_dpp_db
    environment:
      POSTGRES_USER: user-iter-open
      POSTGRES_PASSWORD: psswd-iter-open
      POSTGRES_DB: db-iter-open
      DB_ENV: dev
    networks:
      - internal_network
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - open_dpp_pg:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user-iter-open -d db-iter-open']
      interval: 5s
      timeout: 5s
      retries: 5

# Compose networks
networks:
  internal_network:
    driver: bridge
  public_network:
    external: true

volumes:
  open_dpp_pg:
