sonar.projectKey=Marguillat_iter-open-api_c71af3b1-3e57-4a62-8673-d1e7e0e6ccf6
sonar.sources=./open-api
sonar.go.coverage.reportPaths=./open-api/output/tests/coverage.out
sonar.tests=./open-api
sonar.test.inclusions=**/*_test.go
