# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  registry: ghcr.io
  image_name: ${{ github.repository }}

jobs:
  security:
    name: Snyk Scan api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Run Security Checks
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=open-api/go.mod

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Test open api
        run: cd ./open-api && go test -v

  quality:
    name: Analyze api code with SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [security, tests]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get repo
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PrepareReg Names # Pour virer les majuscule de con
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./open-api
          push: true
          platforms: linux/amd64 # ,linux/arm64 : build sur plusieurs plateformes prend un temps fou en GH-actions
          tags: ${{ env.registry }}/${{ env.IMAGE_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-and-push]
    permissions:
      contents: read
      packages: read
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.5
        env:
          CR_USER: ${{ github.actor }}
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CR_USER,CR_PAT
          script: |
            cd /home/ubuntu/apps/iter

            # 1. Log into GHCR on the VPS server using the passed variables
            echo "$CR_PAT" | docker login ghcr.io -u "$CR_USER" --password-stdin

            echo "pulling images ..."
            docker compose pull

            echo "downing containers ..."
            docker compose down

            echo "composing images ..."
            docker compose up -d --remove-orphans

            # 2. Optional: Logout after you are done to protect the temporary token
            docker logout ghcr.io

            echo "deleting unused content"
            docker system prune -a -f
