name: Security Checks

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  security-API:
    name: Snyk Scan api
    runs-on: ubuntu-latest
    environment: Security
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Run Security Checks
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=open-api/go.mod

  security-FRONT:
    name: Snyk Scan FRONT
    runs-on: ubuntu-latest
    environment: Security
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd open-front && npm ci

      - name: Run Security Checks
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=open-front/package.json
